# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tlogistics\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0bGeoLocation\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"%\n\x10GetParcelRequest\x12\x11\n\tparcel_id\x18\x01 \x01(\t\"\xf2\x01\n\x15ParcelDetailsResponse\x12\x11\n\tparcel_id\x18\x01 \x01(\t\x12\x17\n\x0ftracking_number\x18\x02 \x01(\t\x12\'\n\x06status\x18\x03 \x01(\x0e\x32\x17.logistics.ParcelStatus\x12\x0e\n\x06weight\x18\x04 \x01(\x01\x12\x12\n\nis_fragile\x18\x05 \x01(\x08\x12\x30\n\x10\x63urrent_location\x18\x06 \x01(\x0b\x32\x16.logistics.GeoLocation\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"U\n\x13UpdateStatusRequest\x12\x11\n\tparcel_id\x18\x01 \x01(\t\x12+\n\nnew_status\x18\x02 \x01(\x0e\x32\x17.logistics.ParcelStatus\"W\n\x14UpdateStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12.\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"k\n\x16TelemetryStreamRequest\x12\x11\n\tparcel_id\x18\x01 \x01(\t\x12(\n\x08location\x18\x02 \x01(\x0b\x32\x16.logistics.GeoLocation\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\"D\n\x17TelemetryStreamResponse\x12\x18\n\x10points_processed\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08*\xa0\x01\n\x0cParcelStatus\x12\x1d\n\x19PARCEL_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15PARCEL_STATUS_PENDING\x10\x01\x12\x1c\n\x18PARCEL_STATUS_IN_TRANSIT\x10\x02\x12\x1b\n\x17PARCEL_STATUS_DELIVERED\x10\x03\x12\x1b\n\x17PARCEL_STATUS_CANCELLED\x10\x04\x32\x97\x02\n\x0fTrackingService\x12Q\n\x10GetParcelDetails\x12\x1b.logistics.GetParcelRequest\x1a .logistics.ParcelDetailsResponse\x12U\n\x12UpdateParcelStatus\x12\x1e.logistics.UpdateStatusRequest\x1a\x1f.logistics.UpdateStatusResponse\x12Z\n\x0fStreamTelemetry\x12!.logistics.TelemetryStreamRequest\x1a\".logistics.TelemetryStreamResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARCELSTATUS']._serialized_start=753
  _globals['_PARCELSTATUS']._serialized_end=913
  _globals['_GEOLOCATION']._serialized_start=61
  _globals['_GEOLOCATION']._serialized_end=111
  _globals['_GETPARCELREQUEST']._serialized_start=113
  _globals['_GETPARCELREQUEST']._serialized_end=150
  _globals['_PARCELDETAILSRESPONSE']._serialized_start=153
  _globals['_PARCELDETAILSRESPONSE']._serialized_end=395
  _globals['_UPDATESTATUSREQUEST']._serialized_start=397
  _globals['_UPDATESTATUSREQUEST']._serialized_end=482
  _globals['_UPDATESTATUSRESPONSE']._serialized_start=484
  _globals['_UPDATESTATUSRESPONSE']._serialized_end=571
  _globals['_TELEMETRYSTREAMREQUEST']._serialized_start=573
  _globals['_TELEMETRYSTREAMREQUEST']._serialized_end=680
  _globals['_TELEMETRYSTREAMRESPONSE']._serialized_start=682
  _globals['_TELEMETRYSTREAMRESPONSE']._serialized_end=750
  _globals['_TRACKINGSERVICE']._serialized_start=916
  _globals['_TRACKINGSERVICE']._serialized_end=1195
# @@protoc_insertion_point(module_scope)
