# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackingServiceStub:
    """Опис сервісу міжсервісної взаємодії
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParcelDetails = channel.unary_unary(
                '/logistics.TrackingService/GetParcelDetails',
                request_serializer=service__pb2.GetParcelRequest.SerializeToString,
                response_deserializer=service__pb2.ParcelDetailsResponse.FromString,
                _registered_method=True)
        self.UpdateParcelStatus = channel.unary_unary(
                '/logistics.TrackingService/UpdateParcelStatus',
                request_serializer=service__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=service__pb2.UpdateStatusResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.stream_unary(
                '/logistics.TrackingService/StreamTelemetry',
                request_serializer=service__pb2.TelemetryStreamRequest.SerializeToString,
                response_deserializer=service__pb2.TelemetryStreamResponse.FromString,
                _registered_method=True)


class TrackingServiceServicer:
    """Опис сервісу міжсервісної взаємодії
    """

    def GetParcelDetails(self, request, context):
        """1. Unary RPC: Отримання інформації про вантаж
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateParcelStatus(self, request, context):
        """2. Unary RPC: Оновлення статусу вантажу
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request_iterator, context):
        """3. Client Streaming RPC: Безперервна передача GPS-координат від IoT-датчика
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParcelDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParcelDetails,
                    request_deserializer=service__pb2.GetParcelRequest.FromString,
                    response_serializer=service__pb2.ParcelDetailsResponse.SerializeToString,
            ),
            'UpdateParcelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParcelStatus,
                    request_deserializer=service__pb2.UpdateStatusRequest.FromString,
                    response_serializer=service__pb2.UpdateStatusResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=service__pb2.TelemetryStreamRequest.FromString,
                    response_serializer=service__pb2.TelemetryStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logistics.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logistics.TrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackingService:
    """Опис сервісу міжсервісної взаємодії
    """

    @staticmethod
    def GetParcelDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logistics.TrackingService/GetParcelDetails',
            service__pb2.GetParcelRequest.SerializeToString,
            service__pb2.ParcelDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateParcelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logistics.TrackingService/UpdateParcelStatus',
            service__pb2.UpdateStatusRequest.SerializeToString,
            service__pb2.UpdateStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/logistics.TrackingService/StreamTelemetry',
            service__pb2.TelemetryStreamRequest.SerializeToString,
            service__pb2.TelemetryStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
